### ISSUE TITLE
Plugin doesn't work with the new version of TestRail (7.2)

### ISSUE THREAD

**Issue by trooperjey01** [DamianOsipiuk/testcafe-reporter-testrail#27]
Hi, 

Since the deployment of TestRail 7.2 this week, I can't send any test results to TestRail. I have the following error :

    "ERROR The "reportTaskDone" method of the "testrail" reporter produced an uncaught error. Error details: TypeError: caseList.map is not a function

**Comment by DamianOsipiuk** [comment]
Hi, that is correct.
Testrail made breaking API change.
As I do not use Testrail anymore in day-2-day work, and they do not provide an OpenAPI spec file, upgrade will be quite tedious.
Also, I do not have access to any working Testrail instance, so i need to think how to handle that.

**Comment by chaps** [comment]
Hi, @trooperjey01 , @DamianOsipiuk , I have the same issue.
I noticed this and made some changes to solve it locally but I wonder if this new TestRail version will produce a new `testrail-js-api` version. 
https://github.com/DamianOsipiuk/testcafe-reporter-testrail/pull/29

*Just saw that  `testrail-js-api` it's also yours @DamianOsipiuk

**Comment by DamianOsipiuk** [comment]
@chaps @trooperjey01 Could you test https://github.com/DamianOsipiuk/testcafe-reporter-testrail/releases/tag/v0.8.0 if it would work for you?
There might be an issue if you will have more than 250 elements for a particular call, but we can fix that later.

**Comment by chaps** [comment]
> @chaps @trooperjey01 Could you test https://github.com/DamianOsipiuk/testcafe-reporter-testrail/releases/tag/v0.8.0 if it would work for you?
> There might be an issue if you will have more than 250 elements for a particular call, but we can fix that later.

@DamianOsipiuk Sure, let me take a look and I'll reply how that goes. Thank you!

**Comment by trooperjey01** [comment]
> @chaps @trooperjey01 Could you test https://github.com/DamianOsipiuk/testcafe-reporter-testrail/releases/tag/v0.8.0 if it would work for you?
> There might be an issue if you will have more than 250 elements for a particular call, but we can fix that later.

@DamianOsipiuk, @chaps thanks for your answers. I'll soon try your update and I'll reply too

**Comment by chaps** [comment]
Small test, but looks good from my side, thanks @DamianOsipiuk 
<img width="1022" alt="Screen Shot 2021-09-25 at 17 58 28" src="https://user-images.githubusercontent.com/1173254/134790636-bcadd4b8-9860-4aed-a731-3b48d48e6250.png">
<img width="1101" alt="Screen Shot 2021-09-25 at 17 59 31" src="https://user-images.githubusercontent.com/1173254/134790638-2662a964-0d9e-4a24-b210-9cdb94e17e79.png">
<img width="1250" alt="Screen Shot 2021-09-25 at 17 59 49" src="https://user-images.githubusercontent.com/1173254/134790639-7382e34d-68f2-4882-8e2a-cd82c6c63702.png">

**Comment by trooperjey01** [comment]
Hi, I've run some tests and looks good too. I have a new warning but screenshots and results are sent to TestRail. 

<img width="601" alt="Screenshot_2" src="https://user-images.githubusercontent.com/64835399/135041521-25b32f89-98b7-494f-ba7e-27a3f5995033.png"> 

Thanks a lot! :-)

P.S: I am not comfortable with it but I will try to contribute to the project too.

**Comment by DamianOsipiuk** [comment]
@trooperjey01 Those warning mean that you have code with CID mapping that does not exist in TestRail. Either it's a typo or those test cases have been removed from TestRail.
